# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FootballStats' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FootballStats
	pod 'Alamofire', '~> 5.8.0'
	pod 'SDWebImage', '~> 5.0'
	pod 'RxSwift', '~> 6.6.0'
	pod 'RxCocoa', '~> 6.6.0'
	pod 'RxRelay', '~> 6.6.0'
end
