# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FootballStats' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FootballStats
	pod 'Alamofire', '~> 5.8.0'
	pod 'SDWebImage', '~> 5.0'
	pod 'RxSwift', '~> 5.1'
	pod 'RxCocoa', '~> 5.1'
	pod 'RxRelay', '~> 5.1'
	pod 'RxSwiftUtilities', '~> 2.2.0'
 	pod 'MBProgressHUD'
	pod 'Reusable', '~> 4.1.2'
	pod 'Then', '~> 3.0.0'
end
